name: 'Adapter Smoke Tests'

description: 'Validates changes to an adapter.'

inputs:
  allow-warnings:
    type: boolean
    description: 'Indicates if warnings should be allowed when linting the podspec'
    required: false
    default: false

runs:
  using: 'composite'
  steps:

      # Check out the repo.
    - name: Checkout
      uses: actions/checkout@v3

    # Check that the adapter version in the podpsec and in the PartnerAdapter Swift implementation are the same.
    - name: Validate Adapter and Podspec Version Match
      run: ruby "${{ github.action_path }}/../scripts/validate-adapter-version.rb"
      shell: bash

    # Validate the podspec.
    - name: Validate Podspec
      run: pod lib lint --verbose ${{ inputs.allow-warnings && '--allow-warnings' || '' }}
      shell: bash
