name: 'Adapter Smoke Tests'

description: 'Validates changes to an adapter.'

runs:
  using: 'composite'
  steps:

      # Check out the repo.
    - name: Checkout
      uses: actions/checkout@v3

    # Check that the adapter version in the podpsec and in the PartnerAdapter Swift implementation are the same.
    - name: Validate Adapter and Podspec Version Match
      run: ruby ./Scripts/validate-adapter-version.rb
      shell: bash

    # Validate the podspec.
    - name: Validate Podspec
      run: pod lib lint --verbose
      shell: bash
