name: 'Adapter Smoke Tests'

description: 'Validates changes to an adapter.'

inputs:
  allow-warnings:
    type: boolean
    description: 'Indicates if warnings should be allowed when linting the podspec'
    required: false
    default: false

runs:
  using: 'composite'
  steps:

      # Check out the repo.
    - name: Checkout
      uses: actions/checkout@v3

    # Check that the adapter version in the podpsec and in the PartnerAdapter Swift implementation are the same.
    - name: Validate Adapter and Podspec Version Match
      run: ruby "${{ github.action_path }}/../scripts/adapters/validate-adapter-version.rb"
      shell: bash

    # Check that all source files have the proper copyright headers.
    - name: Validate Copyright Headers
      run: ruby "${{ github.action_path }}/../scripts/adapters/validate-copyright-headers.rb"
      shell: bash

    # Validate the podspec.
    - name: Validate Podspec
      run: pod lib lint --verbose ${{ inputs.allow-warnings == 'true' && '--allow-warnings' || '' }}
      shell: bash

    # Fix the CB SDK version in the podspec to the lowest one compatible with the adapter.
    - name: Lower CB SDK Dependency Version
      run: ruby "${{ github.action_path }}/../scripts/adapters/fix-podspec-cb-sdk-version-to-min.rb"
      shell: bash

    # Ensure adapter backward compatibility with the first minor version of the CB SDK major series.
    - name: Ensure Backward Compatibility
      run: pod lib lint --verbose ${{ inputs.allow-warnings == 'true' && '--allow-warnings' || '' }}
      shell: bash

    # Discard changes made to the podspec file
    - name: Discard Podspec Changes
      if: always()
      run: ruby "${{ github.action_path }}/../scripts/adapters/discard-podspec-changes.rb"
      shell: bash
