name: 'Release Adapter'

description: 'Releases a new adapter version.'

runs:
  using: 'composite'
  steps:
  
    # Check out the repo.
    - name: Checkout Branch
      uses: actions/checkout@v3

    # Obtain the new adapter version.
    - name: Obtain Adapter Version
      id: release_version
      run: echo "version=$(ruby ./scripts/adapter-version.rb)" >> $GITHUB_OUTPUT
      shell: bash

    # Push the release tag.
    - name: Tag
      run: git tag ${{ steps.release_version.outputs.version }} && git push origin ${{ steps.release_version.outputs.version }}
      shell: bash

    # Push the podspec.
    - name: Push Podspec
      run: pod trunk push --verbose
      shell: bash

    # Create GitHub release.
    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.release_version.outputs.version }}
        release_name: ${{ steps.release_version.outputs.version }}
        body: ''
        draft: false
        prerelease: false
