# Releases a new version of the actions by pushing a tag.

name: 'Release'

inputs:
  version:
    type: string
    description: 'The new version'
    required: true
    default: 'v1.0.0'

on:
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

jobs:
  release:
    steps:
      
    # Check out the repo.
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ env.GITHUB_TOKEN }}

    # Validate version string is well-formed and not already released.
    - name: Validate Version String
      run: ruby ./scripts/validate-new-actions-release-version.rb "${{ inputs.version }}"
      shell: bash

    # Run tests.
    - name: Tests
      uses: ./test

    # Obtain the corresponding major version.
    - name: Obtain Major Version
      id: major-version
      run: echo "version=$(ruby ./scripts/major-version-tag-name.rb ${{ inputs.version }})" >> $GITHUB_OUTPUT
      shell: bash

    # Push the release tag.
    - name: Release Tag
      run: git tag ${{ inputs.version }} && git push origin ${{ inputs.version }}
      shell: bash

    # Create/replace major version tag on the same commit as the new release tag.
    - name: Major Version Tag
      run: git tag -f ${{ steps.major-version.outputs.version }} ${{ inputs.version }} && git push -f origin ${{ steps.major-version.outputs.version }}
      shell: bash
